include:
  - component: $CI_SERVER_FQDN/dependabot-gitlab/dependabot-standalone/template@3.38.0
    inputs:
      gitlab_access_token: "${SETTINGS_DEPENDABOT_STANDALONE_GITLAB_ACCESS_TOKEN}"
      github_access_token: "${SETTINGS_DEPENDABOT_STANDALONE_GITHUB_ACCESS_TOKEN}"
      dependabot_gitlab_version: 3.13.3-alpha.1
    rules:
      - if: $PACKAGE_MANAGER_SET

job:
  script:
    - echo "test"
